### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Licoy** [denty/test_wx_echarts#1]
```js
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'getAttribute' of undefined 
 TypeError: Cannot read property 'getAttribute' of undefined
    at Ri (http://127.0.0.1:55877/appservice/ec-canvas/echarts.js:1:35782)
    at rs (http://127.0.0.1:55877/appservice/ec-canvas/echarts.js:1:85245)
    at Object.t.init (http://127.0.0.1:55877/appservice/ec-canvas/echarts.js:1:728718)
    at PieChartPage.initChart (http://127.0.0.1:55877/appservice/page/pie-chart-page.js:65:33)
    at new PieChartPage (http://127.0.0.1:55877/appservice/page/pie-chart-page.js:52:31)
    at Object.$createPage (http://127.0.0.1:55877/appservice/npm/wepy/lib/base.js:140:20)
    at http://127.0.0.1:55877/appservice/page/pie-chart-page.js:118:51
    at require (http://127.0.0.1:55877/appservice/__dev__/WAService.js:18:20970)
    at http://127.0.0.1:55877/appservice/appservice:1268:9
```

**Comment by linkxsystem** [comment]
请问这个问题解决了吗，我运行这个项目出现了同样的问题

**Comment by denty** [comment]
已经处理,更新就好
